---
# tasks file for roles/upgrade-host

- name: upgrade by pacman
  pacman:
    update_cache: true
    upgrade: true
  register: pacman_upgrade
  retries: 5
  until: pacman_upgrade is success
  notify: "reboot"
  when: ansible_distribution == "Archlinux"

- name: upgrade by apt
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success
  notify: "reboot"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
