---
# 06-create-user tasks file for roles/flash-alarm-node

- name: Create user | create user {{ default_user }}
  shell: "chroot {{ dir_install }}/sd-root /bin/bash -c \"useradd -m {{ default_user }}; echo -e '{{ vault_default_password }}\n{{ vault_default_password }}' | passwd {{ default_user }}\""

- name: Create user | authorize {{ default_user }} to use sudo
  lineinfile:
    path: "{{ dir_install }}/sd-root/etc/sudoers.d/{{ default_user }}-allow-to-sudo"
    state: present
    line: "{{ default_user }} ALL=(ALL) NOPASSWD: ALL"
    create: true

- name: Create user | lock other users
  shell: "chroot {{ dir_install }}/sd-root /bin/bash -c \"passwd -l alarm; passwd -l root\""

- name: Create user | delete alarm user
  shell: "chroot {{ dir_install }}/sd-root /bin/bash -c \"userdel -r alarm\""
