---
- hosts: chief
  remote_user: "{{ default_user }}"
  become: true
  gather_facts: true

  pre_tasks:
  - name: list block devices
    command: lsblk -f
    register: blk_list

  - debug:
      msg: "{{ blk_list.stdout_lines }}"

  - pause:
      prompt: enter SD card device full name (/dev/ included; verify that mountpoint is empty!)
    register: dev_sd

  - pause:
      prompt: enter the desired hostname
    register: sd_hostname

  - pause:
      prompt: Choose node role (c = first manager m = additional manager, w = worker, anything else = standalone node not connected to cluster)
    register: node_role

  - pause:
      prompt: |
        Select hardware you are flashing SD card for
          2 = RPi 2 or RPi 3 with full HW support
          3 = RPi 3 with generic kernel
          4 = RPi 4 with generic kernel
    register: image_choice

  - set_fact:
      dev_sd: "{{ dev_sd.user_input }}"

  - set_fact:
      sd_hostname: "{{ sd_hostname.user_input }}"

  - set_fact:
      node_role: "{{ node_role.user_input }}"

  - set_fact:
      image_choice: "{{ image_choice.user_input }}"

  roles:
  - flash-alarm-node
